#!/usr/bin/env python3
"""Decide which .rodata input sections stay in cartridge ROM.

The N64's PI bus only answers word-sized reads. A byte or halfword load from
cartridge space comes back with data from the wrong offset (see n64.ld), so
anything the game reads with a `u8 *` or `u16 *` has to live in RDRAM. The
whole 6.3 MB of .rodata does not fit there, but the parts that do not fit are
exactly the parts that never get read that way: tile graphics, palettes, font
glyph bitmaps, sound banks and multiboot images, all of which reach the game
through DMA or through the decompressors, which read words.

So: emit a linker fragment naming those bulk blobs, which n64.ld places in a
ROM-resident output section ahead of the RDRAM one. Everything not named here
-- every string, struct table and lookup table the compiler emitted -- falls
through to RDRAM and can be read a byte at a time like normal memory.

Selection is by symbol name and size together. The name patterns pick out
graphics-shaped data, and the size floor keeps the small descriptor structs
that happen to be named after their graphics (a CompressedSpriteSheet, a
SpritePalette, a Tileset) in RDRAM, since those *are* read field by field.

Usage: n64_rodata_split.py <out.ld> <object files...>
"""

import re
import subprocess
import sys

# Objects that are nothing but bulk data blobs, kept in ROM wholesale. These
# are assembled from .s files, so every byte lands in one unnamed .rodata.
ROM_OBJECT_BASENAMES = {
    "sound_data.o",
    "multiboot_pokemon_colosseum.o",
    "multiboot_ereader.o",
    "multiboot_berry_glitch_fix.o",
}

# Names that mark raw pixel/colour/glyph data.
GFX_NAME = re.compile(
    r"(Gfx|Tilemap|Tiles|Glyphs|Pic|Palette|Pal$|Pals$|_4bpp|_8bpp|Image)", re.I
)

# ...except these, which are descriptors or game data that merely read like
# graphics. Metatiles in particular are u16 arrays the field code indexes
# directly.
NOT_GFX_NAME = re.compile(r"(Metatile|Template|Sheet|Table|Info|Anims?$)", re.I)

# Below this, a match is far more likely to be a descriptor struct than an
# actual blob, and the space saved would not matter anyway.
MIN_BLOB_SIZE = 256


def sections(obj):
    out = subprocess.run(
        ["mipsel-linux-gnu-objdump", "-h", obj], capture_output=True, text=True
    ).stdout
    for line in out.split("\n"):
        f = line.split()
        if len(f) == 7 and f[1].startswith(".rodata"):
            yield f[1], int(f[2], 16)


def main():
    out_path = sys.argv[1]
    objs = sys.argv[2:]

    names = set()
    total = 0

    for obj in objs:
        whole_object = obj.rsplit("/", 1)[-1] in ROM_OBJECT_BASENAMES
        for name, size in sections(obj):
            if whole_object:
                # An unnamed .rodata would match every object's, so pull the
                # whole file in by name instead.
                continue
            if not name.startswith(".rodata."):
                continue
            symbol = name[len(".rodata."):]
            if size < MIN_BLOB_SIZE:
                continue
            if not GFX_NAME.search(symbol) or NOT_GFX_NAME.search(symbol):
                continue
            if name not in names:
                names.add(name)
                total += size

    with open(out_path, "w") as f:
        f.write("/* Generated by tools/n64_rodata_split.py -- do not edit. */\n")
        for obj in objs:
            if obj.rsplit("/", 1)[-1] in ROM_OBJECT_BASENAMES:
                f.write("%s(.rodata .rodata.*)\n" % obj)
        for name in sorted(names):
            f.write("*(%s)\n" % name)

    print(
        "rodata split: %d sections (%.2f MB) kept in ROM" % (len(names), total / 1048576.0),
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
